<?php
/**
 * ANDREA AI — ONE-SHOT WEB SETUP
 *
 * USAGE: visit  https://www.andreapiani.com/setup-web.php?token=df2fddf788becda3d88ef7948a47aafd
 *
 * After successful run this file renames itself to setup-web.done.php and
 * cannot be re-executed. Delete the renamed file once everything works.
 *
 * What it does:
 *  1. Verifies the one-time token below.
 *  2. Creates data/auth/users.json with admin user "andrea" and the api_token below
 *     (the same api_token is already configured on Vercel as PHP_API_TOKEN).
 *  3. Writes a snippet you must paste into your main .htaccess to set
 *     AAI_IP_SALT and AAI_CRON_TOKEN as environment variables.
 *  4. Renders all credentials on screen.
 *
 * Generated by Claude Code on 2026-04-26.
 */

require_once __DIR__ . "/lib/storage.php";
require_once __DIR__ . "/lib/util.php";

const SETUP_TOKEN = "df2fddf788becda3d88ef7948a47aafd";

$given = $_GET["token"] ?? "";
if (!hash_equals(SETUP_TOKEN, $given)) {
    http_response_code(403);
    echo "Forbidden — invalid setup token.";
    exit;
}

// 1. Create admin user with predetermined credentials so they match Vercel env
$username  = "andrea";
$password  = "TK8ChMMpGK5gfWt";
$apiToken  = "3de8426a154396d7bdb87058588685ca5c4bb97fab040c95f16166d21aad074c";

aai_atomic_update(AAI_USERS, function($cur) use ($username, $password, $apiToken) {
    // Wipe any previous andrea entry
    $cur = array_values(array_filter($cur, fn($u) => is_array($u) && ($u["username"] ?? "") !== $username));
    $cur[] = [
        "username"      => $username,
        "password_hash" => password_hash($password, PASSWORD_ARGON2ID),
        "api_token"     => $apiToken,
        "created_at"    => date("c"),
    ];
    return $cur;
});
@chmod(AAI_USERS, 0600);

// 2. Self-disable
$me = __FILE__;
$done = __DIR__ . "/setup-web.done.php";
@rename($me, $done);

// 3. Render
header("Content-Type: text/html; charset=utf-8");
?>
<!doctype html>
<html lang="it"><head>
<meta charset="utf-8"><title>Andrea AI — setup OK</title>
<meta name="robots" content="noindex,nofollow">
<style>
  body{font-family:ui-sans-serif,system-ui,Arial;max-width:760px;margin:30px auto;padding:0 18px;color:#0f172a;background:#f5f7fb}
  h1{color:#10b981}
  .card{background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:18px;margin:16px 0}
  .ok{background:#d1fae5;color:#065f46;padding:10px 14px;border-radius:6px;margin-bottom:14px}
  pre{background:#0f172a;color:#fbbf24;padding:14px;border-radius:8px;overflow-x:auto;font-size:13px;line-height:1.5}
  code{background:#f1f5f9;padding:2px 6px;border-radius:4px;font-size:13px}
  .warn{background:#fef3c7;color:#92400e;padding:12px;border-radius:6px;font-size:14px;margin:10px 0}
  .danger{background:#fee2e2;color:#991b1b;padding:12px;border-radius:6px;font-size:14px}
  ul li{margin:6px 0}
</style></head><body>

<h1>✓ Setup completato</h1>
<div class="ok">L'utente <strong>andrea</strong> è stato creato. Questo file si è auto-rinominato in <code>setup-web.done.php</code> e non può essere rieseguito.</div>

<div class="card">
  <h2>1. Credenziali admin panel PHP</h2>
  <p>Salva queste credenziali (le potrai cambiare dopo dal pannello in Impostazioni).</p>
  <pre>URL:      https://www.andreapiani.com/admin/login.php
Username: andrea
Password: <?= htmlspecialchars($password) ?></pre>
</div>

<div class="card">
  <h2>2. .htaccess — DA AGGIUNGERE</h2>
  <p>Aggiungi queste 2 righe al file <code>.htaccess</code> nella root del sito. Senza questi env, il backend usa salt di default <strong>insicuri</strong>.</p>
  <pre>SetEnv AAI_IP_SALT "5462cba8c9fa2c314d103464e738b6a4667bcab25cb78d0cd4a15766be94be93"
SetEnv AAI_CRON_TOKEN "e3ad3a2429c7e08f8889682f1bfe39e4080766acf77f704b"</pre>
  <p style="font-size:13px;color:#475569">Se non sai dove sta il <code>.htaccess</code>: è già nella root del sito (lo usi per HTTPS redirect e www redirect). Aggiungi le 2 righe in fondo.</p>
</div>

<div class="card">
  <h2>3. Cron settimanale (purge retention)</h2>
  <p>Su <a href="https://cron-job.org" target="_blank">cron-job.org</a> (free) crea un job settimanale (es. domenica 03:00 GET):</p>
  <pre>https://www.andreapiani.com/api/cron/purge.php?token=e3ad3a2429c7e08f8889682f1bfe39e4080766acf77f704b</pre>
</div>

<div class="card">
  <h2>4. Dashboard Vercel — già pronta</h2>
  <p>La dashboard Vercel <strong>è già stata deployata</strong> con il token API che hai sotto. Funzionerà appena chiudi questa pagina.</p>
  <pre>API token (già su Vercel come PHP_API_TOKEN):
3de8426a154396d7bdb87058588685ca5c4bb97fab040c95f16166d21aad074c

Password dashboard Vercel:
I05Ps78KSiQFMw</pre>
  <p style="font-size:13px;color:#475569">Il dominio Vercel ti viene comunicato dopo il deploy.</p>
</div>

<div class="warn">
  <strong>⚠️ Pulizia:</strong> dopo aver verificato che <code>/admin/login.php</code> e la dashboard Vercel funzionano, <strong>cancella</strong> il file <code>setup-web.done.php</code> dal server (via FTP/cPanel). Contiene credenziali in chiaro.
</div>

<div class="danger">
  <strong>🔒 Importante:</strong> non salvare queste credenziali in chiaro né condividerle via email. Ti consiglio password manager (1Password, Bitwarden).
</div>

</body></html>
